<h1>Содержание<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Подготовка-данных" data-toc-modified-id="Подготовка-данных-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Подготовка данных</a></span><ul class="toc-item"><li><span><a href="#Описание-проекта" data-toc-modified-id="Описание-проекта-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Описание проекта</a></span></li><li><span><a href="#Описание-данных" data-toc-modified-id="Описание-данных-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Описание данных</a></span></li><li><span><a href="#Открываем-и-изучаем-файл" data-toc-modified-id="Открываем-и-изучаем-файл-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Открываем и изучаем файл</a></span></li><li><span><a href="#Предобработка-данных" data-toc-modified-id="Предобработка-данных-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Предобработка данных</a></span><ul class="toc-item"><li><span><a href="#Проведение-лемматизации-и-обработка-символов" data-toc-modified-id="Проведение-лемматизации-и-обработка-символов-1.4.1"><span class="toc-item-num">1.4.1&nbsp;&nbsp;</span>Проведение лемматизации и обработка символов</a></span></li><li><span><a href="#Разбивка-на-обучающую-и-тестовую-выборки" data-toc-modified-id="Разбивка-на-обучающую-и-тестовую-выборки-1.4.2"><span class="toc-item-num">1.4.2&nbsp;&nbsp;</span>Разбивка на обучающую и тестовую выборки</a></span></li><li><span><a href="#Создание-корпуса" data-toc-modified-id="Создание-корпуса-1.4.3"><span class="toc-item-num">1.4.3&nbsp;&nbsp;</span>Создание корпуса</a></span></li><li><span><a href="#Добавление-стоп-слов" data-toc-modified-id="Добавление-стоп-слов-1.4.4"><span class="toc-item-num">1.4.4&nbsp;&nbsp;</span>Добавление стоп-слов</a></span></li><li><span><a href="#Датафрейм-для-сбора-результатов" data-toc-modified-id="Датафрейм-для-сбора-результатов-1.4.5"><span class="toc-item-num">1.4.5&nbsp;&nbsp;</span>Датафрейм для сбора результатов</a></span></li><li><span><a href="#Функция-для-обучения-моделей" data-toc-modified-id="Функция-для-обучения-моделей-1.4.6"><span class="toc-item-num">1.4.6&nbsp;&nbsp;</span>Функция для обучения моделей</a></span></li></ul></li><li><span><a href="#Вывод" data-toc-modified-id="Вывод-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Вывод</a></span></li></ul></li><li><span><a href="#Обучение" data-toc-modified-id="Обучение-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Обучение</a></span><ul class="toc-item"><li><span><a href="#Векторизация" data-toc-modified-id="Векторизация-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>Векторизация</a></span></li><li><span><a href="#Обучение-с-помощью-TF-IDF" data-toc-modified-id="Обучение-с-помощью-TF-IDF-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span>Обучение с помощью <code>TF-IDF</code></a></span></li><li><span><a href="#Обучение-с-помощью-DistilBert" data-toc-modified-id="Обучение-с-помощью-DistilBert-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span>Обучение с помощью <code>DistilBert</code></a></span></li></ul></li><li><span><a href="#Выводы" data-toc-modified-id="Выводы-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Выводы</a></span></li><li><span><a href="#Чек-лист-проверки" data-toc-modified-id="Чек-лист-проверки-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Чек-лист проверки</a></span></li></ul></div>

# Проект для «Викишоп»

Обучите модель классифицировать комментарии на позитивные и негативные. В вашем распоряжении набор данных с разметкой о токсичности правок.

Постройте модель со значением метрики качества *F1* не меньше 0.75. 

**Инструкция по выполнению проекта**

1. Загрузите и подготовьте данные.
2. Обучите разные модели. 
3. Сделайте выводы.

## Подготовка данных

### Описание проекта

Интернет-магазин **«Викишоп»** запускает новый сервис. Теперь пользователи могут редактировать и дополнять описания товаров, как в вики-сообществах. То есть клиенты предлагают свои правки и комментируют изменения других. Магазину нужен инструмент, который будет искать токсичные комментарии и отправлять их на модерацию.

### Описание данных

Данные находятся в файле **`toxic_comments.csv`**. Столбец **`text`** в нём содержит текст комментария, а **`toxic`** — целевой признак.

### Открываем и изучаем файл

Импортируем необходимые в работе библиотеки и модули:

In [1]:
import pandas as pd
import numpy as np

import nltk
nltk.download('punkt')
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

import torch
import transformers

import re
from tqdm import notebook

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score

import lightgbm as lgb

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Алексей\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [2]:
# откроем датасет и сохраним его в новой переменной
df = pd.read_csv('C:\\Users\\Алексей\\Downloads\\toxic_comments.csv')

In [3]:
# выведем первые пять строк таблицы
df.head()

text  toxic
0  Explanation\nWhy the edits made under my usern...      0
1  D'aww! He matches this background colour I'm s...      0
2  Hey man, I'm really not trying to edit war. It...      0
3  "\nMore\nI can't make any real suggestions on ...      0
4  You, sir, are my hero. Any chance you remember...      0

In [4]:
# Выведем информацию по датасету
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 159571 entries, 0 to 159570
Data columns (total 2 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   text    159571 non-null  object
 1   toxic   159571 non-null  int64 
dtypes: int64(1), object(1)
memory usage: 2.4+ MB


In [5]:
# посмотрим на дисбаланс классов
df['toxic'].value_counts()

0    143346
1     16225
Name: toxic, dtype: int64

Как видим дисбаланс классов в данных большой.

### Предобработка данных

#### Проведение лемматизации и обработка символов

В предобработке данных проведем лемматизацию, удалим цифры, а также знаки и лишние пробелы:

In [6]:
# напишем функцию по предобработке
def data_preprocessing(text):
    tokenized = nltk.word_tokenize(text)
    joined = ' '.join(tokenized)
    text_only = re.sub(r'[^a-zA-Z]', ' ', joined)
    final = ' '.join(text_only.split())
    return final

In [7]:
# посмторим как выглядят данные перед обработкой
df['text'][0]

"Explanation\nWhy the edits made under my username Hardcore Metallica Fan were reverted? They weren't vandalisms, just closure on some GAs after I voted at New York Dolls FAC. And please don't remove the template from the talk page since I'm retired now.89.205.38.27"

In [8]:
# обработаем данные и сохраним результат в новом столбце
notebook.tqdm.pandas() 
df['text_final'] = df['text'].progress_apply(data_preprocessing)

  0%|          | 0/159571 [00:00<?, ?it/s]

In [9]:
# посмторим как выглядят данные после обработки
df['text_final'][0]

'Explanation Why the edits made under my username Hardcore Metallica Fan were reverted They were n t vandalisms just closure on some GAs after I voted at New York Dolls FAC And please do n t remove the template from the talk page since I m retired now'

#### Разбивка на обучающую и тестовую выборки

In [10]:
x_df = df['text_final'] # признаки
y_df = df['toxic'] # целевое значение

In [11]:
# задаем значение random_state
rand = 13

# разбиваем на выборки и выводим на экран
x_train_df, x_test_df, y_train_df, y_test_df = train_test_split(x_df, y_df, random_state=rand, stratify=y_df)
x_train_df.shape, x_test_df.shape, y_train_df.shape, y_test_df.shape

((119678,), (39893,), (119678,), (39893,))

Посмотрим на распределение классов в выборках:

In [12]:
print('Распределение классов в обучающей выборке:')
print("Класс '0' =", y_train_df.value_counts()[0] / y_train_df.value_counts().sum() * 100)
print("Класс '1' =", y_train_df.value_counts()[1] / y_train_df.value_counts().sum() * 100)
print()
print('Распределение классов в тестовой выборке:')
print("Класс '0' =", y_test_df.value_counts()[0] / y_test_df.value_counts().sum() * 100)
print("Класс '1' =", y_test_df.value_counts()[1] / y_test_df.value_counts().sum() * 100)

Распределение классов в обучающей выборке:
Класс '0' = 89.83188221728304
Класс '1' = 10.168117782716957

Распределение классов в тестовой выборке:
Класс '0' = 89.83280274734916
Класс '1' = 10.16719725265084


#### Создание корпуса

Создадим корпус:

In [13]:
x_train_df_corpus = x_train_df.values.astype('U')
x_test_df_corpus = x_test_df.values.astype('U')

#### Добавление стоп-слов

Добавим стоп-слова:

In [14]:
# загрузим список стоп-слов
nltk.download('stopwords')
# вызовем функцию stopwords.words(), передадим ей аргумент 'english', то есть англоязычные стоп-слова
stopwords = set(stopwords.words('english'))
print("Количество стоп-слов = ", len(stopwords))

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Алексей\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


Количество стоп-слов =  179


#### Датафрейм для сбора результатов

Подготовим датафрейм для сбора результатов:

In [15]:
results = pd.DataFrame({
    'Preprocessing model' : [],
    'Learning model' : [],
    'Train f1 score' : [],
    'Test f1 score' : []
})

In [16]:
models = [
    LogisticRegression(max_iter=1000),
    lgb.LGBMClassifier(n_estimators = 1000, learning_rate = 0.1)
]

#### Функция для обучения моделей

Напишем функцию для обучения моделей:

In [17]:
def function_training_models(models_list, x_train, y_train, x_test, y_test, preprocess_model : str):
    for i in models_list:
        clf_gs = GridSearchCV(i, {}, cv=5, scoring='f1')
        clf_gs.fit(x_train,y_train)
        
        train_f1_score = f1_score(y_train, clf_gs.predict(x_train))
        test_f1_score = f1_score(y_test, clf_gs.predict(x_test))
        
        name = str(i).split(sep='(')[0]
        
        globals()['results'] = globals()['results'].append({
            'Preprocessing model' : preprocess_model, 'Learning model' : name, 
            'Train f1 score' : round(train_f1_score, 2), 'Test f1 score' : round(test_f1_score, 2)}, 
            ignore_index=True)

### Вывод

Мы открыли и изучили файл с данными, а также сохранили его в отдельной переменной. Провели предобработку данных: лемматизировали и обработали символы путем удаления цифр, знаков и лишних пробелов, а также произвели разбивку данных на обучающую и тестовую выборки. Создали корпус и добавили стоп-слова. Подготовили датафрейм для сбора результатов и написали функцию для обучения моделей.

## Обучение

### Векторизация

Создадим счетчик:

In [18]:
# передадим список стоп-слов в счётчик векторов CountVectorizer()
vectorizer = CountVectorizer(stop_words=stopwords, dtype=np.float32)

In [19]:
# передадим счётчику корпус текстов через функцию fit_transform()
x_train_df_vectorized = vectorizer.fit_transform(x_train_df_corpus)
x_test_df_vectorized = vectorizer.transform(x_test_df_corpus)

In [20]:
print(x_train_df_vectorized.shape)
print()
print(x_train_df_vectorized[:5].toarray())

(119678, 142782)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [21]:
%%time
function_training_models(models, 
                         x_train_df_vectorized, y_train_df, 
                         x_test_df_vectorized, y_test_df, 
                         preprocess_model = 'CountVectorizer')

<ipython-input-17-361fd388f50a>:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  globals()['results'] = globals()['results'].append({


Wall time: 9min 5s
Parser   : 266 ms


<ipython-input-17-361fd388f50a>:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  globals()['results'] = globals()['results'].append({


In [22]:
results[-2:]

Preprocessing model      Learning model  Train f1 score  Test f1 score
0     CountVectorizer  LogisticRegression            0.90           0.75
1     CountVectorizer      LGBMClassifier            0.92           0.76

### Обучение с помощью `TF-IDF`

Проведем обучение с помощью TF-IDF

In [23]:
tf_idf = TfidfVectorizer(stop_words=stopwords)

In [24]:
x_train_df_tf_idf = tf_idf.fit_transform(x_train_df)
x_test_df_tf_idf = tf_idf.transform(x_test_df)

In [25]:
print(x_train_df_tf_idf.shape)
print()
print(x_train_df_tf_idf[:5].toarray())

(119678, 142782)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [26]:
%%time
function_training_models(models, x_train_df_tf_idf, y_train_df, x_test_df_tf_idf, y_test_df,
             preprocess_model = 'TfidfVectorizer')

<ipython-input-17-361fd388f50a>:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  globals()['results'] = globals()['results'].append({


Wall time: 25min 40s


<ipython-input-17-361fd388f50a>:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  globals()['results'] = globals()['results'].append({


In [27]:
results[-2:]

Preprocessing model      Learning model  Train f1 score  Test f1 score
2     TfidfVectorizer  LogisticRegression            0.76           0.72
3     TfidfVectorizer      LGBMClassifier            0.95           0.77

### Обучение с помощью `DistilBert`

Для ускорения обучения модели `Bert`, возьмем срез из 2000 строк из основного датафрейма.

Проверим сохранен ли в срезе дисбаланс классов основного датафрейма:

In [28]:
print('Распределение классов во всем датасете:')
print(df['toxic'].value_counts()[0] / df['toxic'].value_counts().sum() * 100)
print(df['toxic'].value_counts()[1] / df['toxic'].value_counts().sum() * 100)
print()
print('Распределение классов в срезе для Bert:')
print(df['toxic'][:2000].value_counts()[0] / df['toxic'][:2000].value_counts().sum() * 100)
print(df['toxic'][:2000].value_counts()[1] / df['toxic'][:2000].value_counts().sum() * 100)

Распределение классов во всем датасете:
89.83211235124176
10.167887648758233

Распределение классов в срезе для Bert:
89.5
10.5


In [29]:
model_class, tokenizer_class, pretrained_weights = (transformers.DistilBertModel, transformers.DistilBertTokenizer, 
                                                    'distilbert-base-uncased')

In [30]:
tokenizer = tokenizer_class.from_pretrained(pretrained_weights)
model = model_class.from_pretrained(pretrained_weights)

Downloading:   0%|          | 0.00/226k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/28.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/483 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/256M [00:00<?, ?B/s]

Some weights of the model checkpoint at distilbert-base-uncased were not used when initializing DistilBertModel: ['vocab_layer_norm.weight', 'vocab_projector.weight', 'vocab_layer_norm.bias', 'vocab_projector.bias', 'vocab_transform.weight', 'vocab_transform.bias']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


#### Tokenization

In [31]:
tokenized = df['text_final'][:2000].progress_apply(lambda x: tokenizer.encode(x[:512], add_special_tokens=True))

  0%|          | 0/2000 [00:00<?, ?it/s]

#### Padding

In [32]:
len(tokenized[0])

56

In [33]:
padded = np.array([i + [0]*(512-len(i)) for i in tokenized.values])

In [34]:
len(padded[0])

512

#### Masking

In [35]:
attention_mask = np.where(padded != 0, 1, 0)
padded.shape, attention_mask.shape

((2000, 512), (2000, 512))

In [36]:
batch_size = 10
embeddings = []

In [37]:
for i in notebook.tqdm(range(padded.shape[0] // batch_size)):
    batch = torch.LongTensor(padded[batch_size*i:batch_size*(i+1)])
    attention_mask_batch = torch.LongTensor(attention_mask[batch_size*i:batch_size*(i+1)])
    
    with torch.no_grad():
        batch_embeddings = model(batch, attention_mask=attention_mask_batch)
    embeddings.append(batch_embeddings[0][:,0,:].numpy())

  0%|          | 0/200 [00:00<?, ?it/s]

In [38]:
x_bert = np.concatenate(embeddings)
y_bert = df['toxic'][:2000]
x_bert.shape, y_bert.shape

((2000, 768), (2000,))

In [39]:
x_train_bert, x_test_bert, y_train_bert, y_test_bert = train_test_split(x_bert, y_bert, random_state=rand, stratify=y_bert)

In [40]:
%%time
function_training_models(models, x_train_bert, y_train_bert, x_test_bert, y_test_bert,
             preprocess_model = 'DistilBert')

<ipython-input-17-361fd388f50a>:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  globals()['results'] = globals()['results'].append({


Wall time: 1min 52s


<ipython-input-17-361fd388f50a>:11: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  globals()['results'] = globals()['results'].append({


In [41]:
results[-2:]

Preprocessing model      Learning model  Train f1 score  Test f1 score
4          DistilBert  LogisticRegression            0.84           0.75
5          DistilBert      LGBMClassifier            1.00           0.62

## Выводы

Посмотрим на таблицу результатов

In [42]:
results.sort_values('Test f1 score', ascending=False)

Preprocessing model      Learning model  Train f1 score  Test f1 score
3     TfidfVectorizer      LGBMClassifier            0.95           0.77
1     CountVectorizer      LGBMClassifier            0.92           0.76
0     CountVectorizer  LogisticRegression            0.90           0.75
4          DistilBert  LogisticRegression            0.84           0.75
2     TfidfVectorizer  LogisticRegression            0.76           0.72
5          DistilBert      LGBMClassifier            1.00           0.62

Наилучший результат показала модель **`LGBMClassifier`** на предобработанном тексте с помощью модели **`TfidfVectorizer`**. Возможно `DistilBert` показал плохой результат из-за того, что был обучен всего на 2000 строках, в то время как остальные модели на всем датафрейме.